#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
%define keepstatic 1
Name     : rustc
Version  : 1.54.0
Release  : 90
URL      : file:///aot/build/clearlinux/packages/rustc/rust-1.54.0.tar.gz
Source0  : file:///aot/build/clearlinux/packages/rustc/rust-1.54.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 GPL-2.0
Requires: rustc-bin = %{version}-%{release}
Requires: rustc-data = %{version}-%{release}
Requires: rustc-libexec = %{version}-%{release}
Requires: rustc-man = %{version}-%{release}
Requires: rustc-bin
Requires: rustc-data
Requires: rustc-dev
Requires: rustc-doc
Requires: rustc-libexec
Requires: rustc-man
Requires: rustc-staticdev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
# Ignore missing build ids
%undefine _missing_build_ids_terminate_build
# Disable automatic requeriments processing
AutoReq: no

%description
# The Rust Programming Language
This is the main source code repository for [Rust]. It contains the compiler,
standard library, and documentation.

%package bin
Summary: bin components for the rustc package.
Group: Binaries
Requires: rustc-data = %{version}-%{release}
Requires: rustc-libexec = %{version}-%{release}
# Disable automatic requeriments processing
AutoReq: no

%description bin
bin components for the rustc package.


%package data
Summary: data components for the rustc package.
Group: Data
# Disable automatic requeriments processing
AutoReq: no

%description data
data components for the rustc package.


%package dev
Summary: dev components for the rustc package.
Group: Development
Requires: rustc-bin = %{version}-%{release}
Requires: rustc-data = %{version}-%{release}
Provides: rustc-devel = %{version}-%{release}
Requires: rustc = %{version}-%{release}
# Disable automatic requeriments processing
AutoReq: no

%description dev
dev components for the rustc package.


%package doc
Summary: doc components for the rustc package.
Group: Documentation
Requires: rustc-man = %{version}-%{release}
# Disable automatic requeriments processing
AutoReq: no

%description doc
doc components for the rustc package.


%package libexec
Summary: libexec components for the rustc package.
Group: Default
# Disable automatic requeriments processing
AutoReq: no

%description libexec
libexec components for the rustc package.


%package man
Summary: man components for the rustc package.
Group: Default
# Disable automatic requeriments processing
AutoReq: no

%description man
man components for the rustc package.


%package staticdev
Summary: staticdev components for the rustc package.
Group: Default
Requires: rustc-dev = %{version}-%{release}
# Disable automatic requeriments processing
AutoReq: no

%description staticdev
staticdev components for the rustc package.


%prep
%setup -q -n rust-nightly-x86_64-unknown-linux-gnu
cd %{_builddir}/rust-nightly-x86_64-unknown-linux-gnu

%build
unset http_proxy
unset https_proxy
unset no_proxy
export SSL_CERT_FILE=/var/cache/ca-certs/anchors/ca-certificates.crt
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1622623749
export GCC_IGNORE_WERROR=1
## altflags1 content
export CFLAGS="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC"
# -ffat-lto-objects -fno-PIE -fno-PIE -m64 -no-pie -fpic -fvisibility=hidden -flto-partition=none
# gcc: -feliminate-unused-debug-types -fipa-pta -flto=16 -Wno-error -Wp,-D_REENTRANT -fno-common
export CXXFLAGS="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -fvisibility-inlines-hidden -pipe -ffat-lto-objects -fPIC"
#
export FCFLAGS="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC"
export FFLAGS="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC"
export CFFLAGS="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC"
#
export LDFLAGS="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC"
#
export AR=/usr/bin/gcc-ar
export RANLIB=/usr/bin/gcc-ranlib
export NM=/usr/bin/gcc-nm
#
export MAKEFLAGS=%{?_smp_mflags}
#
%global _lto_cflags 1
#global _lto_cflags %{nil}
#
# export PATH="/usr/lib64/ccache/bin:$PATH"
# export CCACHE_NOHASHDIR=1
# export CCACHE_DIRECT=1
# export CCACHE_SLOPPINESS=pch_defines,locale,time_macros
# export CCACHE_DISABLE=1
#
#global _privatelibs lib.*-[[:xdigit:]]*[.]so.*
#global __provides_exclude ^(%{_privatelibs})$
#global __requires_exclude ^(%{_privatelibs})$
%global _privatelibs lib(.*-[[:xdigit:]]{16}*|rustc.*)[.]so.*
%global __provides_exclude ^(%{_privatelibs})$
%global __requires_exclude ^(%{_privatelibs})$
%global __provides_exclude_from ^(%{_docdir}|/usr/rustlib/src)/.*$
%global __requires_exclude_from ^(%{_docdir}|/usr/rustlib/src)/.*$
## altflags1 end
## make_macro content
echo "Installing..."
# /builddir/build/BUILDROOT/ /builddir/build/BUILDROOT/rustc-64.unknown.gnu-73.x86_64
## make_macro end


%install
export SOURCE_DATE_EPOCH=1622623749
rm -rf %{buildroot}
## install_macro start
./install.sh --prefix=%{?buildroot:%{buildroot}}/usr/ --libdir=%{?buildroot:%{buildroot}}/usr/lib/ --disable-ldconfig --without=rust-docs --verbose
#./install.sh --destdir=%{?buildroot:%{buildroot}} --prefix=/usr/ --libdir=/usr/lib/ --disable-ldconfig --without=rust-docs --verbose
# shell completion for bash
install -dm 0755 %{buildroot}/usr/share/bash-completion/completions
install -m0644  %{buildroot}/usr/etc/bash_completion.d/cargo %{buildroot}/usr/share/bash-completion/completions/cargo
rm -rf %{buildroot}/usr/etc/bash_completion.d/cargo
#
find %{?buildroot:%{buildroot}} -name "install.log" -exec rm {} \;
# find %{?buildroot:%{buildroot}} -type f -name '*manifest-*' -exec sed -i 's/\/builddir\/build\/BUILDROOT\/rustc-[0-9]*\.unknown\.gnu-[0-9]*\.x86_64//g' {} \;
#find %{?buildroot:%{buildroot}} -type f -name '*manifest-*' -exec sed -i 's/\/builddir\/build\/BUILDROOT\/rustc-(\d+)(\.\d+)*-[0-9]*\.x86_64//g' {} \;
#pushd %{?buildroot:%{buildroot}}
#rg -e "/builddir/build/BUILDROOT/"
#popd
#rustc-1.54.0-90.x86_64
find %{buildroot}/usr/lib/rustlib/ -maxdepth 1 -type f -exec rm -v '{}' '+'
## install_macro end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/cargo
/usr/bin/cargo-clippy
/usr/bin/cargo-fmt
/usr/bin/cargo-miri
/usr/bin/clippy-driver
/usr/bin/miri
/usr/bin/rust-analyzer
/usr/bin/rust-demangler
/usr/bin/rust-gdb
/usr/bin/rust-gdbgui
/usr/bin/rust-lldb
/usr/bin/rustc
/usr/bin/rustdoc
/usr/bin/rustfmt
/usr/lib/rustlib/x86_64-unknown-linux-gnu/bin/llc
/usr/lib/rustlib/x86_64-unknown-linux-gnu/bin/llvm-ar
/usr/lib/rustlib/x86_64-unknown-linux-gnu/bin/llvm-as
/usr/lib/rustlib/x86_64-unknown-linux-gnu/bin/llvm-cov
/usr/lib/rustlib/x86_64-unknown-linux-gnu/bin/llvm-dis
/usr/lib/rustlib/x86_64-unknown-linux-gnu/bin/llvm-nm
/usr/lib/rustlib/x86_64-unknown-linux-gnu/bin/llvm-objcopy
/usr/lib/rustlib/x86_64-unknown-linux-gnu/bin/llvm-objdump
/usr/lib/rustlib/x86_64-unknown-linux-gnu/bin/llvm-profdata
/usr/lib/rustlib/x86_64-unknown-linux-gnu/bin/llvm-readobj
/usr/lib/rustlib/x86_64-unknown-linux-gnu/bin/llvm-size
/usr/lib/rustlib/x86_64-unknown-linux-gnu/bin/llvm-strip
/usr/lib/rustlib/x86_64-unknown-linux-gnu/bin/opt
/usr/lib/rustlib/x86_64-unknown-linux-gnu/bin/rust-lld
/usr/lib/rustlib/x86_64-unknown-linux-gnu/bin/rust-llvm-dwp

%files data
%defattr(-,root,root,-)
/usr/share/bash-completion/completions/cargo
/usr/share/zsh/site-functions/_cargo

%files dev
%defattr(-,root,root,-)
/usr/lib/libLLVM-12-rust-1.54.0-nightly.so
/usr/lib/librustc_driver-f0cc9de4b9df9abc.so
/usr/lib/libstd-d3e6744d0f396e66.so
/usr/lib/libtest-7a39810ff79f839d.so
/usr/lib/rustlib/etc/gdb_load_rust_pretty_printers.py
/usr/lib/rustlib/etc/gdb_lookup.py
/usr/lib/rustlib/etc/gdb_providers.py
/usr/lib/rustlib/etc/lldb_commands
/usr/lib/rustlib/etc/lldb_lookup.py
/usr/lib/rustlib/etc/lldb_providers.py
/usr/lib/rustlib/etc/rust_types.py
/usr/lib/rustlib/x86_64-unknown-linux-gnu/analysis/libaddr2line-f99e7382840549d7.json
/usr/lib/rustlib/x86_64-unknown-linux-gnu/analysis/libadler-d7fdb8a364254f09.json
/usr/lib/rustlib/x86_64-unknown-linux-gnu/analysis/liballoc-e6deb9eb350bb778.json
/usr/lib/rustlib/x86_64-unknown-linux-gnu/analysis/libcfg_if-e05d5bbb424526aa.json
/usr/lib/rustlib/x86_64-unknown-linux-gnu/analysis/libcompiler_builtins-5316ae3464026e70.json
/usr/lib/rustlib/x86_64-unknown-linux-gnu/analysis/libcore-c8ded1707ad10767.json
/usr/lib/rustlib/x86_64-unknown-linux-gnu/analysis/libgetopts-944f5cc1e3634038.json
/usr/lib/rustlib/x86_64-unknown-linux-gnu/analysis/libgimli-006a52b07ae6fce1.json
/usr/lib/rustlib/x86_64-unknown-linux-gnu/analysis/libhashbrown-63bc2a12f0584ef8.json
/usr/lib/rustlib/x86_64-unknown-linux-gnu/analysis/liblibc-1079ae9f5c548531.json
/usr/lib/rustlib/x86_64-unknown-linux-gnu/analysis/libminiz_oxide-54e5dcc22cacb214.json
/usr/lib/rustlib/x86_64-unknown-linux-gnu/analysis/libobject-376f281ac00de390.json
/usr/lib/rustlib/x86_64-unknown-linux-gnu/analysis/libpanic_abort-af7832c9d0f158f9.json
/usr/lib/rustlib/x86_64-unknown-linux-gnu/analysis/libpanic_unwind-ddc7d21207d48a7c.json
/usr/lib/rustlib/x86_64-unknown-linux-gnu/analysis/libproc_macro-001c25393a3d064a.json
/usr/lib/rustlib/x86_64-unknown-linux-gnu/analysis/libprofiler_builtins-68d026a1182dc377.json
/usr/lib/rustlib/x86_64-unknown-linux-gnu/analysis/librustc_demangle-accb84145985d6d8.json
/usr/lib/rustlib/x86_64-unknown-linux-gnu/analysis/librustc_std_workspace_alloc-604e1b8f7fcab9a7.json
/usr/lib/rustlib/x86_64-unknown-linux-gnu/analysis/librustc_std_workspace_core-2588c44e3ecacf72.json
/usr/lib/rustlib/x86_64-unknown-linux-gnu/analysis/librustc_std_workspace_std-622591ee636daa45.json
/usr/lib/rustlib/x86_64-unknown-linux-gnu/analysis/libstd-d3e6744d0f396e66.json
/usr/lib/rustlib/x86_64-unknown-linux-gnu/analysis/libstd_detect-7f24f1eba37e8be9.json
/usr/lib/rustlib/x86_64-unknown-linux-gnu/analysis/libterm-f7df501eeb74b3ff.json
/usr/lib/rustlib/x86_64-unknown-linux-gnu/analysis/libtest-7a39810ff79f839d.json
/usr/lib/rustlib/x86_64-unknown-linux-gnu/analysis/libunicode_width-04c349d9941e0616.json
/usr/lib/rustlib/x86_64-unknown-linux-gnu/analysis/libunwind-68bf8b1f361d5008.json
/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libLLVM-12-rust-1.54.0-nightly.so
/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libaddr2line-f99e7382840549d7.rlib
/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libadler-d7fdb8a364254f09.rlib
/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-e6deb9eb350bb778.rlib
/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-e05d5bbb424526aa.rlib
/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-5316ae3464026e70.rlib
/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-c8ded1707ad10767.rlib
/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgetopts-944f5cc1e3634038.rlib
/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgimli-006a52b07ae6fce1.rlib
/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-63bc2a12f0584ef8.rlib
/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-1079ae9f5c548531.rlib
/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libminiz_oxide-54e5dcc22cacb214.rlib
/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libobject-376f281ac00de390.rlib
/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_abort-af7832c9d0f158f9.rlib
/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-ddc7d21207d48a7c.rlib
/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libproc_macro-001c25393a3d064a.rlib
/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libprofiler_builtins-68d026a1182dc377.rlib
/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-accb84145985d6d8.rlib
/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-604e1b8f7fcab9a7.rlib
/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-2588c44e3ecacf72.rlib
/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_std-622591ee636daa45.rlib
/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-d3e6744d0f396e66.rlib
/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-d3e6744d0f396e66.so
/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd_detect-7f24f1eba37e8be9.rlib
/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libterm-f7df501eeb74b3ff.rlib
/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libtest-7a39810ff79f839d.rlib
/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libtest-7a39810ff79f839d.so
/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunicode_width-04c349d9941e0616.rlib
/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-68bf8b1f361d5008.rlib

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/cargo/LICENSE-APACHE
/usr/share/doc/cargo/LICENSE-MIT
/usr/share/doc/cargo/LICENSE-THIRD-PARTY
/usr/share/doc/cargo/README.md
/usr/share/doc/clippy/LICENSE-APACHE
/usr/share/doc/clippy/LICENSE-MIT
/usr/share/doc/clippy/README.md
/usr/share/doc/miri/LICENSE-APACHE
/usr/share/doc/miri/LICENSE-MIT
/usr/share/doc/miri/README.md
/usr/share/doc/rust-analyzer/LICENSE-APACHE
/usr/share/doc/rust-analyzer/LICENSE-MIT
/usr/share/doc/rust-analyzer/README.md
/usr/share/doc/rust-demangler/LICENSE-APACHE
/usr/share/doc/rust-demangler/LICENSE-MIT
/usr/share/doc/rust-demangler/README.md
/usr/share/doc/rust/COPYRIGHT
/usr/share/doc/rust/LICENSE-APACHE
/usr/share/doc/rust/LICENSE-MIT
/usr/share/doc/rust/README.md
/usr/share/doc/rustfmt/LICENSE-APACHE
/usr/share/doc/rustfmt/LICENSE-MIT
/usr/share/doc/rustfmt/README.md

%files libexec
%defattr(-,root,root,-)
/usr/libexec/cargo-credential-1password

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/cargo-bench.1
/usr/share/man/man1/cargo-build.1
/usr/share/man/man1/cargo-check.1
/usr/share/man/man1/cargo-clean.1
/usr/share/man/man1/cargo-doc.1
/usr/share/man/man1/cargo-fetch.1
/usr/share/man/man1/cargo-fix.1
/usr/share/man/man1/cargo-generate-lockfile.1
/usr/share/man/man1/cargo-help.1
/usr/share/man/man1/cargo-init.1
/usr/share/man/man1/cargo-install.1
/usr/share/man/man1/cargo-locate-project.1
/usr/share/man/man1/cargo-login.1
/usr/share/man/man1/cargo-metadata.1
/usr/share/man/man1/cargo-new.1
/usr/share/man/man1/cargo-owner.1
/usr/share/man/man1/cargo-package.1
/usr/share/man/man1/cargo-pkgid.1
/usr/share/man/man1/cargo-publish.1
/usr/share/man/man1/cargo-run.1
/usr/share/man/man1/cargo-rustc.1
/usr/share/man/man1/cargo-rustdoc.1
/usr/share/man/man1/cargo-search.1
/usr/share/man/man1/cargo-test.1
/usr/share/man/man1/cargo-tree.1
/usr/share/man/man1/cargo-uninstall.1
/usr/share/man/man1/cargo-update.1
/usr/share/man/man1/cargo-vendor.1
/usr/share/man/man1/cargo-verify-project.1
/usr/share/man/man1/cargo-version.1
/usr/share/man/man1/cargo-yank.1
/usr/share/man/man1/cargo.1
/usr/share/man/man1/rustc.1
/usr/share/man/man1/rustdoc.1

%files staticdev
%defattr(-,root,root,-)
/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc-nightly_rt.asan.a
/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc-nightly_rt.lsan.a
/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc-nightly_rt.msan.a
/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc-nightly_rt.tsan.a
